# Generated by Django 4.2.3 on 2024-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='remind_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_description', models.CharField(blank=True, max_length=200, null=True)),
                ('remind_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
