# Generated by Django 4.2.3 on 2024-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind_user',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
