# Generated by Django 4.2.3 on 2024-03-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remind_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.remind_user'),
        ),
        migrations.AlterField(
            model_name='remind_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
