# Generated by Django 4.2.3 on 2024-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reminder_email_reminder_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind_user',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='remind_user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
