# Generated by Django 4.2.3 on 2024-03-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_reminder_email_remove_reminder_remind_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='remind_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
