# Generated by Django 4.2.3 on 2024-03-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reminder_remind_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='remind_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_status',
        ),
    ]
