# Generated by Django 4.2.3 on 2024-03-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reminder_email_reminder_remind_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
