# Generated by Django 4.2.3 on 2024-03-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reminder_reminder_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind_user',
            name='email',
        ),
    ]
